export const agentDetail = [
        {
            "emailId": "muhammad.ahmad@valcom.ae",
            "hr": "geocelh.geraldizo@valcom.ae",
            "gender": "Male",
            "approvalStatus": "Approval Not Enabled",
            "secondReportingTo": "",
            "department": "Sales",
            "totalExperienceDisplayValue": "3 month(s)",
            "employeeStatus": "Resigned",
            "experience": "0",
            "otherEmail": "ahmad.ahsan2012@gmail.com",
            "locationName": "The Hive",
            "totalExperience": "3",
            "reportingToMailId": null,
            "zohoId": 676223000002049006,
            "designation": "Property Consultant",
            "ageDisplayValue": "37 year(s) 8 month(s)",
            "firstName": "Muhammad Ahmad Rana",
            "religion": "Islam",
            "experienceDisplayValue": "3 month(s)",
            "mobile": "971-585858917",
            "nationality": "Pakistan",
            "workPhone": "97144927002",
            "brnDisplayValue": "53792",
            "expertise": "",
            "photo": "https://contacts.zoho.com/file?ID=813366418&fs=thumb",
            "mobileCountryCode": "ae",
            "reportingTo": "Marwan El Choueiry VLC-00028",
            "photoDownloadUrl": "https://contacts.zoho.com/file?ID=813366418&fs=thumb",
            "role": "Team member",
            "employeeType": "Permanent",
            "lastName": "Iftikhar Ahmad",
            "employeeId": "VLC-00313",
            "zuid": "813366418",
            "permanentAddress": "49-C1, Neaspak Housing Society Phase-1, Near Ghazi Chowk,College Road Township,Lahore,Punjab,PAKISTAN,54000",
            "workLocation": "The Hive",
            "presentAddress": "113, First Floor,  Al Shaya Building, back side Park Regis Hotel, Al Karama,Dubai,Dubayy,UNITED ARAB EMIRATES,54000",
            "age": "37",
            "aboutMe": "",
            "extension": "",
            "ethnicity": "",
            "location": "The Hive",
            "brn": "53792",
            "imageUrl": "https://ik.imagekit.io/valcom123/images/agents/813366418.jpg?ver=1693488648536",
            "languageSpoken": null,
            "certifications": null,
            "areasOfExpertise": null
        }
    ]
 