export const buildingData ={
    "pfLocationCommunity": "Business Bay",
    "communitiesDuplexTo": "",
    "numberOfParkingSpaces": "",
    "communitiesApartmentsFrom": "",
    "triplexFrom": "",
    "yearLaunched": "2017",
    "elevators": "6",
    "communitiesArchived": "",
    "buildingType": "Ultra High Rise",
    "serviceCurrencyRate": "",
    "communitiesAccessFromRoads": "",
    "buildingSportsFacilitiesAmenityType": "Building Sports Facilities",
    "buildingSportsFacilities": [
        "Tennis Court"
    ],
    "communitiesGreaterArea": "",
    "communitiesLakes": "",
    "subAreaSubCommunity": "Noora Tower",
    "communitiesMarinaBerths": "",
    "communitiesPublicParking": "",
    "publicParking": "",
    "yearExpectedCompletion": "",
    "buildingFacilities": [
        "Elevators",
        "Service Elevators",
        "Visitors Parking",
        "Basement Parking",
        "Electric Vehicle Charging Stations"
    ],
    "communitiesYearLaunched": "",
    "communitiesArea": "",
    "communitiesServiceCurrency": "",
    "pfLocationSubcommunity": "Al Habtoor City",
    "communitiesNumberOfParkingSpaces": "",
    "plotSqM": "",
    "buildingAttachmentSubform": [
        "Corporate",
        "Corporate",
        "Corporate",
        "Contact",
        "Contact"
    ],
    "buildingAmenities": [
        "Shared Pool",
        "Kids Pool",
        "Shared Gym",
        "Barbecue Area",
        "Lobby Entrance",
        "Pets Allowed"
    ],
    "longitude": "55.26000",
    "communitiesLatitude": "",
    "buildingFacilitiesAmenity": "Elevators,Service Elevators,Visitors Parking,Basement Parking,Electric Vehicle Charging Stations",
    "serviceCurrencyName": "UAE Dirham",
    "streetNoName": "Sheikh Zayed Road",
    "greaterArea": "Temp Greater Area",
    "serviceCurrencyIconURL": "",
    "country": "United Arab Emirates",
    "communitiesTriplexFrom": "",
    "communitiesStreetNoName": "",
    "communityName": "",
    "communitiesZoning": "",
    "propertyTypeZoningCategory": "Building Residential",
    "pfLocationCommunityLocationCity": "Dubai",
    "heightM": "306.94",
    "builtUpSqFt": "",
    "serviceCurrency": "UAE Dirham",
    "communitiesDuplexFrom": "",
    "serviceElevators": "1",
    "communitiesPenthouseFrom": "",
    "communitiesPenthouseTo": "",
    "serviceCurrencyISOCode": "AED",
    "buildingServicesEvents": [
        "Concierge",
        "24 Hours Security",
        "Atm"
    ],
    "communitiesParks": "",
    "zoning": "Freehold",
    "communitiesOwnershipType": "",
    "communitiesServiceChargeSqFt": "",
    "penthouseTo": "7-Beds",
    "inputUnit": "SqFt",
    "pfLocationCity": "Dubai",
    "communityAreaSqFt": "",
    "communitiesLeadImage": "",
    "communitiesReferenceNo": "",
    "communitiesLongitude": "",
    "latitude": "25.18370",
    "archived": "false",
    "ownershipType": "Multiple Owners",
    "nocCharges": "",
    "communitiesNOCCharges": "",
    "pfLocationSubCommunityLocationCommunity": "Business Bay - 4266529000001193448",
    "fireFightingSystem": "Installed",
    "buildingAC": "District Cooling",
    "communitiesState": "",
    "communitiesVillaFrom": "",
    "serviceChargeSqFt": "12.50",
    "communitiesTriplexTo": "",
    "zoningCategory": "Residential",
    "communitiesAutoNumber": "",
    "developmentStatus": "Completed",
    "referenceNo": "B-000139",
    "communitiesApartmentsTo": "",
    "apartmentsTo": "4-Beds",
    "buildingClassification": "Building not yet Classified",
    "propertyType": "Residential Building",
    "city": "Dubai City",
    "petPolicy": "Allowed",
    "autoNumber": "139",
    "communitiesYearCompleted": "",
    "area": "Business Bay",
    "communitiesTownhouseFrom": "",
    "state": "Dubai",
    "duplexTo": "",
    "apartmentsFrom": "1-Beds",
    "district": "Business Bay 1",
    "communitiesParksGreenSpacesSqFt": "",
    "communitiesNumberOfGatesEntries": "",
    "communitiesCity": "",
    "communitiesPetPolicy": "",
    "pfLocationProperty": "Noora",
    "communitiesCountry": "",
    "communitiesYearExpectedCompletion": "",
    "communitiesTownhouseTo": "",
    "yearCompleted": "2020",
    "communitiesNumberOfCompoundsWithinCommunity": "",
    "communitiesParksGreenSpacesSqM": "",
    "communitiesAccessControl": "",
    "serviceCurrencyIsDigitalCurrency": "No",
    "serviceChargeSqM": "0.00",
    "pfLocationPropertyLocationSubCommunity": "Al Habtoor City",
    "leadImage": "",
    "buildingUsage": "Residential",
    "stories": "74",
    "communitiesGolfCourse": "",
    "buildingName": "Noora Tower",
    "communitiesServiceChargeSqM": "",
    "addedTime": "15-Apr-2022 10:02:33",
    "penthouseFrom": "6-Beds",
    "modifiedTime": "12-Mar-2023 23:23:03",
    "plotSqFt": "",
    "residentialUnits": "537",
    "communitiesAreaSqM": "",
    "communitiesVillaTo": "",
    "communitiesInputUnit": "",
    "communitiesEasyAccessibilityToMainRoad": "",
    "heightFt": "1007.00",
    "builtUpAreaSqM": "",
    "communitiesDevelopmentStatus": "",
    "triplexTo": "",
    "duplexFrom": "",
    "crmAssociates": [
        {
            "crmAssociate": "Adel M R Y Behbehani- Ref No: Cn-0002136",
            "crmAssociateType": "Owner"
        },
        {
            "crmAssociate": "Ms. YASHVINDER PUNJABI HARMINDER SINGH HOUDA- Ref No: Cn-0002658",
            "crmAssociateType": "Owner"
        },
        {
            "crmAssociate": "Al Habtoor Group- Ref No: Cr-0000238",
            "crmAssociateType": "Contractor"
        },
        {
            "crmAssociate": "Al Habtoor Group- Ref No: Cr-0000238",
            "crmAssociateType": "Developer"
        },
        {
            "crmAssociate": "Al Habtoor Group- Ref No: Cr-0000238",
            "crmAssociateType": "Master Developer"
        }
    ],
    "message": "SUCCESS",
    "status": "SUCCESS"
}