import { toCarouselArray } from "../utils/utility"



export const omanListings =
toCarouselArray('title',[
        {
            "owner": {
                "name": "Lokesh Shahi",
                "id": null,
                "email": "lokesh.shahi@valcom.ae"
            },
            "alternativeListingTitle": "Great Investment",
            "rentalPeriod": null,
            "devAccess": "Do not show",
            "purchaseDepositAmount": "0",
            "baths": "4",
            "numberOfCheques": null,
            "balconies": "No",
            "subAreaSubCommunity": "Amazi",
            "viewingOptions": "Viewing is not available for this property",
            "id": "5197834000046602001",
            "createdTime": "2023-09-21T18:48:34+04:00",
            "rentalDepositAmount": null,
            "builtUpAreaSqm": "242.94",
            "longitude": "54.3005",
            "beds": "4",
            "referenceNoAuto": "L-006545",
            "nocChargesPercentage": "4",
            "additionalCosts": null,
            "plotAreaSqm": "762.91",
            "nextAvailable": null,
            "streetNumberName": "Hawana roundabout",
            "listingLinkId": "4266529000003615172",
            "greaterArea": "Hawana Salalah",
            "country": "Oman",
            "created_by": {
                "name": "Zoho  Admin",
                "id": null,
                "email": "zohoadmin@valcom.ae"
            },
            "transferFee": "4954.52",
            "amenities": null,
            "titleDeedPercentage": "4",
            "building": null,
            "hidePurchasePrice": "false",
            "titleDeedFee": "4954.52",
            "parkingType": "Unnumbered Parking",
            "purchaseDepositPercentage": null,
            "dtcmPermitNumber": "000000000",
            "recordImage": "41f0e62ade32b4e489deec874436ebc2ab7797070f5fcef9a62ed8923324bbacd4ff5112dbf1f6653e090f0874dd64e5d7d93439097f7aef904eef6c24792149602d119545d26669595a28983acf1ec4",
            "locationOfPropertyKey": "There is no key There is no key There is no key There is no key There is no key There is no key There is no key",
            "trakheesiPermitNumber": "000000000",
            "listCurrency": "Omani rial",
            "plotAreaSqft": "8212.00",
            "hideRentalPrice": "false",
            "creditCardAccepted": false,
            "unitNumber": "101",
            "tag": [],
            "builtUpAreaSqft": "2615.00",
            "exclusive": "Yes",
            "publishingType": "Public listing",
            "latitude": "17.0334",
            "listingStatus": "Published",
            "communityLongitude": "54.3005",
            "digitalCurrencyAccepted": "Yes",
            "lastActivityTime": "2023-09-25T17:18:12+04:00",
            "name": "L-006545",
            "exclusiveContractStart": "2023-09-22",
            "unsubscribedMode": null,
            "nocCharges": "4954.52",
            "serviceChargeSqft": "0.31",
            "zoningCategory": "Property Residential",
            "referenceNumber": "L-006545",
            "communityStreetAddress": "Hawana Roundabout",
            "yearBuilt": null,
            "propertyType": "Villa",
            "city": "Salalah",
            "utilitiesPremiseNumber": null,
            "rentalPrice": null,
            "parkingQty": null,
            "area": "Hawana Salalah",
            "listingTitle": [
                "Beach Access, High ROI, Great Investment"
            ],
            "state": "Salalah",
            "digiCurrency": "Bitcoin",
            "uniqueExtras": null,
            "priceSqm": "509.85",
            "purchasePrice": "123863",
            "district": null,
            "propertyUsage": "Vacant",
            "trusteeFeePercentage": "4",
            "availableForRent": null,
            "zoningTenure": "Freehold",
            "transferFeePercentage": "4",
            "communityRefNumber": "C-0000070",
            "furnished": "Unfurnished",
            "priceSqft": "47.37",
            "exclusiveContractEnd": "2023-12-01",
            "referenceNumberBuilding": null,
            "availableForSale": null,
            "modified_by": {
                "name": "Zoho  Admin",
                "id": null,
                "email": "zohoadmin@valcom.ae"
            },
            "serviceChargeSqm": "0.03",
            "saleOrRent": "For Sale",
            "terraces": "Yes",
            "stories": "1",
            "listingDescription": "Welcome to Amazi – where luxury meets the serene beauty of Salalah's waterfront. This exceptional residential resort development, brought to you by Muriya, a subsidiary of the esteemed Orascom Development Holding and Oman Tourism Development Company, is the epitome of coastal living. Nestled within the vibrant Hawana Salalah, this integrated tourist destination sets the stage for a lifestyle like no other.\n\nArchitectural Marvel:** The vision of Amazi was brought to life by none other than SB Architect, a globally acclaimed architecture and design firm with a presence in San Francisco, Miami, and Shenzhen. Their expertise has crafted a masterpiece that seamlessly blends modern luxury with the natural splendor of Salalah.\n\nIndulge in Extravagance:** Certain properties within Amazi come complete with staff rooms and private, resort-like swimming pools, adding an extra layer of convenience and luxury to your lifestyle. Revel in the opulence of Omani marble flooring, bask in the glow of natural light through floor-to-ceiling glass doors, and enjoy the spaciousness of 10 ft-high ceilings. Your walk-in closet adds a touch of practicality to the grandeur.\n\nIn Amazi, every detail has been carefully considered to provide you with an unparalleled living experience. Here, you're not just buying a property; you're embracing a lifestyle where luxury, nature, and architectural excellence converge to create your dream oasis in Salalah. Welcome home to Amazi, where luxury knows no bounds, and coastal living becomes an art form.",
            "modifiedTime": "2023-09-25T17:18:12+04:00",
            "completionStatus": "Off-plan",
            "communityLatitude": "17.0334",
            "residentialUnits": null,
            "unsubscribedTime": null,
            "agents": null,
            "rentalDepositPercentage": null,
            "trusteeFee": "4954.52",
            "propertyReferenceNumber": "P-003094",
            "zipPostalCode": "00000",
            "listingTo": null,
            "attachmentCount": null,
            "community": "Amazi",
            "brn": 53792,
            "floor": null,
            "tempBayutReferenceNum": null,
            "tempPropertyFinderReferenceNum": null,
            "portal": "Manseel",
            "expectedYear": 2026,
            "propertyId": "4266529000003602039",
            "view360": null,
            "video": "https://youtu.be/w4tS0LQpILY",
            "propertyStories": null,
            "pfLocationCity": null,
            "pfLocationCommunity": null,
            "pfLocationSubCommunity": null,
            "pfLocationProperty": null,
            "rentTrakheesiPermitNumber": "000000000",
            "agentDB": [],
            "listingImages": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-100-Bedroom.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-101-Bedroom.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-102-Living%20Room.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-103-Living%20Room.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-104-Living%20Room.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-105-Living%20Room.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-106-Property%20View.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-107-Pool.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-109-Bedroom.jpg?ver=20230925171812",
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Image-110-Community%20View.jpg?ver=20230925171812"
            ],
            "listingDocs": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602039/Document-1695306642634_No_Objection_Certificate.pdf?ver=20230925171812"
            ],
            "rentalPricePrevious": null,
            "purchasePricePrevious": "123863"
        },
        {
            "owner": {
                "name": "Dalia Aljack",
                "id": null,
                "email": "dalia.aljack@valcom.ae"
            },
            "alternativeListingTitle": "Investor's Deal",
            "rentalPeriod": null,
            "devAccess": "Do not show",
            "purchaseDepositAmount": "0",
            "baths": "2",
            "numberOfCheques": null,
            "balconies": "No",
            "subAreaSubCommunity": null,
            "viewingOptions": "Viewing is not available for this property",
            "id": "5197834000046608001",
            "createdTime": "2023-09-21T18:52:34+04:00",
            "rentalDepositAmount": null,
            "builtUpAreaSqm": "140.93",
            "longitude": null,
            "beds": "2",
            "referenceNoAuto": "L-006546",
            "nocChargesPercentage": "4",
            "additionalCosts": null,
            "plotAreaSqm": "773.97",
            "nextAvailable": null,
            "streetNumberName": "Hawana roundabout",
            "listingLinkId": null,
            "greaterArea": "Hawana Salalah",
            "country": "Oman",
            "created_by": {
                "name": "Zoho  Admin",
                "id": null,
                "email": "zohoadmin@valcom.ae"
            },
            "transferFee": "2120",
            "amenities": ",",
            "titleDeedPercentage": "4",
            "building": null,
            "hidePurchasePrice": "false",
            "titleDeedFee": "2120",
            "parkingType": "Unnumbered Parking",
            "purchaseDepositPercentage": null,
            "dtcmPermitNumber": "000000000",
            "recordImage": null,
            "locationOfPropertyKey": "There is no key it is still off plan............................................",
            "trakheesiPermitNumber": "000000000",
            "listCurrency": "Omani Riyal",
            "plotAreaSqft": "8331.00",
            "hideRentalPrice": "false",
            "creditCardAccepted": false,
            "unitNumber": "102",
            "tag": [],
            "builtUpAreaSqft": "1517.00",
            "exclusive": "Yes",
            "publishingType": "Public listing",
            "latitude": null,
            "listingStatus": "Published",
            "communityLongitude": null,
            "digitalCurrencyAccepted": "Yes",
            "lastActivityTime": "2023-09-25T15:45:22+04:00",
            "name": "L-006546",
            "exclusiveContractStart": "2023-09-25",
            "unsubscribedMode": null,
            "nocCharges": "2120",
            "serviceChargeSqft": "3.00",
            "zoningCategory": "Property Residential",
            "referenceNumber": "L-006546",
            "communityStreetAddress": null,
            "yearBuilt": null,
            "propertyType": "Villa",
            "city": "Salalah",
            "utilitiesPremiseNumber": null,
            "rentalPrice": null,
            "parkingQty": null,
            "area": "Hawana Salalah",
            "listingTitle": [
                "Beach Access, Waterfront Living, Huge Plot"
            ],
            "state": "Salalah",
            "digiCurrency": null,
            "uniqueExtras": null,
            "priceSqm": "376.07",
            "purchasePrice": "53000",
            "district": null,
            "propertyUsage": "Vacant",
            "trusteeFeePercentage": "4",
            "availableForRent": null,
            "zoningTenure": "Freehold",
            "transferFeePercentage": "4",
            "communityRefNumber": "C-0000070",
            "furnished": "Unfurnished",
            "priceSqft": "34.94",
            "exclusiveContractEnd": "2024-01-01",
            "referenceNumberBuilding": null,
            "availableForSale": null,
            "modified_by": {
                "name": "VALCOM Admin",
                "id": null,
                "email": "rgsindxb@gmail.com"
            },
            "serviceChargeSqm": "0.28",
            "saleOrRent": "For Sale",
            "terraces": "Yes",
            "stories": null,
            "listingDescription": "Welcome to Amazi – where luxury meets the serene beauty of Salalah's waterfront. This exceptional residential resort development, brought to you by Muriya, a subsidiary of the esteemed Orascom Development Holding and Oman Tourism Development Company, is the epitome of coastal living. Nestled within the vibrant Hawana Salalah, this integrated tourist destination sets the stage for a lifestyle like no other.\n\nArchitectural Marvel: The vision of Amazi was brought to life by none other than SB Architect, a globally acclaimed architecture and design firm with a presence in San Francisco, Miami, and Shenzhen. Their expertise has crafted a masterpiece that seamlessly blends modern luxury with the natural splendor of Salalah.\n\nIndulge in Extravagance: Certain properties within Amazi come complete with staff rooms and private, resort-like swimming pools, adding an extra layer of convenience and luxury to your lifestyle. Revel in the opulence of Omani marble flooring, bask in the glow of natural light through floor-to-ceiling glass doors, and enjoy the spaciousness of 10 ft-high ceilings. Your walk-in closet adds a touch of practicality to the grandeur.\n\nIn Amazi, every detail has been carefully considered to provide you with an unparalleled living experience. Here, you're not just buying a property; you're embracing a lifestyle where luxury, nature, and architectural excellence converge to create your dream oasis in Salalah. Welcome home to Amazi, where luxury knows no bounds, and coastal living becomes an art form.",
            "modifiedTime": "2023-09-25T15:45:22+04:00",
            "completionStatus": "Off-plan",
            "communityLatitude": null,
            "residentialUnits": null,
            "unsubscribedTime": null,
            "agents": null,
            "rentalDepositPercentage": null,
            "trusteeFee": "2120",
            "propertyReferenceNumber": "P-003095",
            "zipPostalCode": "00000",
            "listingTo": null,
            "attachmentCount": null,
            "community": "Amazi",
            "brn": 53792,
            "floor": null,
            "tempBayutReferenceNum": null,
            "tempPropertyFinderReferenceNum": null,
            "portal": "Manseel",
            "expectedYear": 2026,
            "propertyId": "4266529000003602059",
            "view360": null,
            "video": "https://youtu.be/w4tS0LQpILY",
            "propertyStories": "1",
            "pfLocationCity": null,
            "pfLocationCommunity": null,
            "pfLocationSubCommunity": null,
            "pfLocationProperty": null,
            "rentTrakheesiPermitNumber": "000000000",
            "agentDB": [],
            "listingImages": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-100-Bedroom.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-101-Bedroom.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-102-Living%20Room.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-103-Living%20Room.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-104-Bedroom.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-105-Living%20Room.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-106-Living%20Room.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-107-Pool.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-109-Bedroom.jpg?ver=20230925154522",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-110-Community%20View.jpg?ver=20230925154522"
            ],
            "listingDocs": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Document-1695305745834_No_Objection_Certificate.pdf?ver=20230925154522"
            ],
            "rentalPricePrevious": null,
            "purchasePricePrevious": "514000"
        },
        {
            "owner": {
                "name": "Moataz Al-Smara",
                "id": null,
                "email": "moataz.alsmara@valcom.ae"
            },
            "alternativeListingTitle": "Commission Free",
            "rentalPeriod": null,
            "devAccess": "Do not show",
            "purchaseDepositAmount": "0",
            "baths": "2",
            "numberOfCheques": null,
            "balconies": "No",
            "subAreaSubCommunity": null,
            "viewingOptions": "Viewing is not available for this property",
            "id": "5197834000046738001",
            "createdTime": "2023-09-22T17:59:26+04:00",
            "rentalDepositAmount": null,
            "builtUpAreaSqm": "140.93",
            "longitude": null,
            "beds": "2",
            "referenceNoAuto": "L-006547",
            "nocChargesPercentage": "4",
            "additionalCosts": null,
            "plotAreaSqm": "773.97",
            "nextAvailable": null,
            "streetNumberName": "Hawana roundabout",
            "listingLinkId": null,
            "greaterArea": "Hawana Salalah",
            "country": "Oman",
            "created_by": {
                "name": "Zoho  Admin",
                "id": null,
                "email": "zohoadmin@valcom.ae"
            },
            "transferFee": "2095.88",
            "amenities": ",",
            "titleDeedPercentage": "4",
            "building": null,
            "hidePurchasePrice": "false",
            "titleDeedFee": "2095.88",
            "parkingType": "Unnumbered Parking",
            "purchaseDepositPercentage": null,
            "dtcmPermitNumber": "000000000",
            "recordImage": null,
            "locationOfPropertyKey": "There is no key\nThere is no key\nThere is no key\nThere is no key",
            "trakheesiPermitNumber": "000000000",
            "listCurrency": "Omani rial",
            "plotAreaSqft": "8331.00",
            "hideRentalPrice": "false",
            "creditCardAccepted": false,
            "unitNumber": "102",
            "tag": [],
            "builtUpAreaSqft": "1517.00",
            "exclusive": "Yes",
            "publishingType": "Public listing",
            "latitude": null,
            "listingStatus": "Published",
            "communityLongitude": null,
            "digitalCurrencyAccepted": "Yes",
            "lastActivityTime": "2023-09-25T15:45:21+04:00",
            "name": "L-006547",
            "exclusiveContractStart": "2023-09-22",
            "unsubscribedMode": null,
            "nocCharges": "2095.88",
            "serviceChargeSqft": "3.00",
            "zoningCategory": "Property Residential",
            "referenceNumber": "L-006547",
            "communityStreetAddress": null,
            "yearBuilt": null,
            "propertyType": "Villa",
            "city": "Salalah",
            "utilitiesPremiseNumber": null,
            "rentalPrice": null,
            "parkingQty": null,
            "area": "Hawana Salalah",
            "listingTitle": [
                "Commission Free, High ROI, Investor's Deal"
            ],
            "state": "Salalah",
            "digiCurrency": "Bitcoin",
            "uniqueExtras": null,
            "priceSqm": "371.79",
            "purchasePrice": "52397",
            "district": null,
            "propertyUsage": "Vacant",
            "trusteeFeePercentage": "4",
            "availableForRent": null,
            "zoningTenure": "Freehold",
            "transferFeePercentage": "4",
            "communityRefNumber": "C-0000070",
            "furnished": "Unfurnished",
            "priceSqft": "34.54",
            "exclusiveContractEnd": "2024-01-01",
            "referenceNumberBuilding": null,
            "availableForSale": null,
            "modified_by": {
                "name": "VALCOM Admin",
                "id": null,
                "email": "rgsindxb@gmail.com"
            },
            "serviceChargeSqm": "0.28",
            "saleOrRent": "For Sale",
            "terraces": "Yes",
            "stories": null,
            "listingDescription": "Welcome to Amazi – where luxury meets the serene beauty of Salalah's waterfront. This exceptional residential resort development, brought to you by Muriya, a subsidiary of the esteemed Orascom Development Holding and Oman Tourism Development Company, is the epitome of coastal living. Nestled within the vibrant Hawana Salalah, this integrated tourist destination sets the stage for a lifestyle like no other.\n\nArchitectural Marvel: The vision of Amazi was brought to life by none other than SB Architect, a globally acclaimed architecture and design firm with a presence in San Francisco, Miami, and Shenzhen. Their expertise has crafted a masterpiece that seamlessly blends modern luxury with the natural splendor of Salalah.\n\nIndulge in Extravagance: Certain properties within Amazi come complete with staff rooms and private, resort-like swimming pools, adding an extra layer of convenience and luxury to your lifestyle. Revel in the opulence of Omani marble flooring, bask in the glow of natural light through floor-to-ceiling glass doors, and enjoy the spaciousness of 10 ft-high ceilings. Your walk-in closet adds a touch of practicality to the grandeur.\n\nIn Amazi, every detail has been carefully considered to provide you with an unparalleled living experience. Here, you're not just buying a property; you're embracing a lifestyle where luxury, nature, and architectural excellence converge to create your dream oasis in Salalah. Welcome home to Amazi, where luxury knows no bounds, and coastal living becomes an art form.",
            "modifiedTime": "2023-09-25T15:45:21+04:00",
            "completionStatus": "Off-plan",
            "communityLatitude": null,
            "residentialUnits": null,
            "unsubscribedTime": null,
            "agents": null,
            "rentalDepositPercentage": null,
            "trusteeFee": "2095.88",
            "propertyReferenceNumber": "P-003095",
            "zipPostalCode": "00000",
            "listingTo": null,
            "attachmentCount": null,
            "community": "Amazi",
            "brn": 53792,
            "floor": null,
            "tempBayutReferenceNum": null,
            "tempPropertyFinderReferenceNum": null,
            "portal": "Manseel",
            "expectedYear": 2026,
            "propertyId": "4266529000003602059",
            "view360": null,
            "video": "https://youtu.be/w4tS0LQpILY",
            "propertyStories": "1",
            "pfLocationCity": null,
            "pfLocationCommunity": null,
            "pfLocationSubCommunity": null,
            "pfLocationProperty": null,
            "rentTrakheesiPermitNumber": "000000000",
            "agentDB": [],
            "listingImages": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-100-Bedroom.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-101-Bedroom.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-102-Living%20Room.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-103-Living%20Room.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-104-Bedroom.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-105-Living%20Room.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-106-Living%20Room.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-107-Pool.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-109-Bedroom.jpg?ver=20230925154521",
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Image-110-Community%20View.jpg?ver=20230925154521"
            ],
            "listingDocs": [
                "https://ik.imagekit.io/valcom123/images/4266529000003602059/Document-1695305745834_No_Objection_Certificate.pdf?ver=20230925154521"
            ],
            "rentalPricePrevious": null,
            "purchasePricePrevious": "52397"
        }
    ],"listingImages")