export const savedSearches = [
  {
    country: "United Arab Emirates",
    city: "Dubai",
    area: ["Business Bay"],
    propertyType: "Any",
    beds: ["4", "6", "7"],
    baths: ["4", "6", "7"],
    price: "Any",
    neighbourhood: [
      "Business Bay",
      "Marina",
      "Motor City",
      "Downtown",
      "Palm Jumeirah",
      "JVC",
      "JLT",
    ],
    building: ["Damac Paramount"],
  },
  {
    country: "United Arab Emirates",
    city: "Dubai",
    area: ["Downtown", "Jebel Ali"],
    propertyType: "Any",
    beds: ["4", "6", "7"],
    baths: ["4", "6", "7"],
    price: "Any",
    neighbourhood: [
      "Business Bay",
      "Marina",
      "Motor City",
      "Downtown",
      "Palm Jumeirah",
      "JVC",
      "JLT",
    ],
    building: ["Damac Paramount"],
  },
  {
    country: "United Arab Emirates",
    city: "Dubai",
    area: ["Business Bay"],
    propertyType: "Any",
    beds: ["4", "6", "7"],
    baths: ["4", "6", "7"],
    price: "Any",
    neighbourhood: [
      "Business Bay",
      "Marina",
      "Motor City",
      "Downtown",
      "Palm Jumeirah",
      "JVC",
      "JLT",
    ],
    building: ["Damac Paramount"],
  },
  {
    country: "United Arab Emirates",
    city: "Dubai",
    area: ["Business Bay"],
    propertyType: "Any",
    beds: ["4", "6", "7"],
    baths: ["4", "6", "7"],
    price: "Any",
    neighbourhood: [
      "Business Bay",
      "Marina",
      "Motor City",
      "Downtown",
      "Palm Jumeirah",
      "JVC",
      "JLT",
    ],
    building: ["Damac Paramount"],
  },
];
