export const CountryZoomLevels = {
  "United Arab Emirates": 6.4,
  "United States": 3.4,
  Oman: 5.2,
};

export const CountryCoordinates = {
  "United Arab Emirates": [54.509965507462056, 24.34223056689067],
  "United States": [-97.9222112121185, 38.3012661305678],
  Oman: [57.025216, 20.900043],
  "Saudi Arabia": [45.0792, 23.8859],
  India: [78.9629, 20.5937],
  Pakistan: [69.3451, 30.3753],

  Germany: [10.4515, 51.1657],
  France: [2.2137, 46.2276],
  // Mexico: [69.3451, 30.3753],
  // Canada: [69.3451, 30.3753],
  // Switzerland: [69.3451, 30.3753],
  // Spain: [69.3451, 30.3753],
  // Brazil: [69.3451, 30.3753],
};

export const stateListElement = {
  "United Arab Emirates": "All Emirates",
  "United States": "All States",
  Oman: "All States",
};

// export const UAEStates = [
//   "All Emirates",
//   "Dubai",
//   "Abu Dhabi",
//   "Sharjah",
//   "Umm Al Quwain",
//   "Fujairah",
//   "Ajman",
//   "Ras Al Khaimah",
// ];

// export const UAEStateCities = {
//   "All Emirates": ["All Cities"],
//   "Abu Dhabi": [
//     "All Cities",
//     "Abu Dhabi City",
//     "Abu al Abyad",
//     "Al-Aryam Island",
//     "Al-Bahiyah",
//     "Al-Shahamah",
//     "Al-Wathbah",
//     "Bani Yas City",
//     "Ghantoot",
//     "Halat al Bahrani",
//     "Jubail Island",
//     "Khalifa Port",
//     "Masdar City",
//     "Mina' Zayed",
//     "Mussafah",
//     "Saadiyat Island",
//     "Yas Island",
//     "Madinat Zayed",
//     "Ghayathi",
//     "Ghuwaifat",
//     "Habshan",
//     "Liwa Oasis",
//     "Marawah Island",
//     "Ruwais",
//     "Sila",
//     "Sir Bani Yas",
//     "Tarif",
//     "Al Ain",
//     "Al-Faqa'",
//     "Al-Hayer",
//     "Al-Qu'a",
//     "Al-Shwaib",
//     "Al-Wagan",
//     "Al-Yahar",
//     "Mezyad",
//     "Nahil",
//     "Remah",
//     "Sa'ah",
//     "Sweihan",
//   ],
//   Dubai: ["All Cities", "Dubai", "Jebel Ali", "Hatta"],
//   Sharjah: [
//     "All Cities",
//     "Sharjah",
//     "Khor Fakkan",
//     "Kalba",
//     "Dhaid",
//     "Dibba Al-Hisn",
//     "Al Madam",
//   ],
//   "Umm Al Quwain": ["Umm al-Quwain"],
//   Fujairah: ["All Cities", "Fujairah", "Dibba Al-Fujairah"],
//   Ajman: ["Ajman"],
//   "Ras Al Khaimah": ["All Cities", "RAK City", "Ar-Rams"],
// };

export const PropertyTypes = [
  "Select All",
  "Apartment",
  "Villa",
  "Townhouse",
  "Hotel Apartment",
  "Duplex Apartment",
  "Penthouse",
  "Lots/Land",
  "Manufactured",
];
