export const listings = [
  {
    _id: "",
    Owner: {
      name: "Marie-Elize Venter",
      id: "5197834000004614001",
      email: "marie@valcom.ae",
    },
    Alternative_Listing_Title: "TERTE",
    Rental_Period: null,
    $field_states: null,
    DevAccess: "Do not show",
    $sharing_permission: "full_access",
    Purchase_Deposit_Amount: "121212",
    Baths: "1",
    $state: "save",
    Number_of_Cheques: null,
    $process_flow: false,
    Balconies: "2",
    Sub_Area_Sub_Community: "Damac Towers by Paramount",
    Viewing_Options: "Viewing can be booked instantly",
    id: "5197834000008264001",
    $approval: {
      delegate: false,
      approve: false,
      reject: false,
      resubmit: false,
    },
    Created_Time: "2022-07-03T22:09:56+02:00",
    Rental_Deposit_Amount: null,
    Built_up_Area_SqM: "200.00",
    Longitude: null,
    Beds: "1",
    Reference_No_Auto: "L-000579",
    NOC_Charges_Perc: "4",
    Additional_Costs: null,
    Plot_Area_SqM: "233.00",
    Next_available: null,
    Street_No_Name: "Cresent West",
    Listing_Link_ID: "4266529000000792032",
    Greater_Area: "Dubailand",
    Country: "United Arab Emirates",
    Created_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    Transfer_Fee: "400000",
    Amenities: "Burj Khalifa View\nBoulevard View\nBroadband Ready",
    Title_Deed_Perc: "4",
    Building: "Damac Tower Paramount B",
    Hide_Purch_Price: false,
    Title_Deed_Fee: "400000",
    $review_process: {
      approve: false,
      reject: false,
      resubmit: false,
    },
    Parking_Type: "Podium 2",
    Purchase_Deposit_Percentage: "1.21",
    Record_Image:
      "a80f4895b5572856d6439a1988025ccf48ec6a723e68f23c846bd873860f11e3d5f91dc9b0659dbf5276f988d8a10226561a69b81019de3f213ee694f6c04fa124804180c0bddd6f81481f473f272951",
    Location_of_Property_Key: "MAT",
    ListCurrency: "Aruban florin",
    Plot_Area_SqFt: "2508.01",
    Hide_Rental_Price: false,
    $orchestration: false,
    Credit_Card_Accepted: false,
    Unit_No: "123123",
    Tag: [],
    Built_up_Area_SqFt: "2152.80",
    $currency_symbol: "$",
    Exclusive: "No",
    Publishing_Type: "Off-market listing",
    Latitude: null,
    $followers: null,
    Listing_Status: "Draft",
    Community_Longitude: "123",
    Digital_Currency_Accepted: "No",
    Last_Activity_Time: "2022-07-03T22:09:59+02:00",
    Name: "L-000579",
    Exclusive_Contract_Start: null,
    Unsubscribed_Mode: null,
    NOC_Charges: "400000",
    $approved: true,
    Reference_No: "L-000579",
    Community_Street_Address: "po box 25874",
    $followed: false,
    $wizard_connection_path: null,
    Year_Built: null,
    $editable: true,
    Property_Type: "Townhouse",
    City: "Dubai City",
    Utilities_Premise_Number: "123",
    Rental_Price: null,
    Parking_Qty: "7",
    Area: "Dubai Marina",
    Listing_Title: ["Golf course view", "Incredible view", "Beach access"],
    State: "Dubai",
    DigiCurrency: null,
    Unique_Extras: "ERER",
    Price_SqM: "50000",
    Purchase_Price: "10000000",
    District: "District 3",
    Property_Usage: "Holiday home",
    Trustee_Fee_Perc: "4",
    Available_for_Rent: false,
    Zoning_Tenure: null,
    Transfer_Fee_Perc: "4",
    Community_Ref_No: "C-0000004",
    Furnished: "Fully furnished",
    Price_SqFt: "4645.11",
    Exclusive_Contract_End: null,
    Ref_No_Building: null,
    Available_for_Sale: false,
    Modified_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    $review: null,
    Sale_or_Rent: "For Sale",
    Terraces: "3",
    Stories: null,
    Listing_Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam sint ad inventore aut illum placeat deserunt eveniet nemo amet, repudiandae repellendus rem ratione, nobis incidunt harum eos at! Rem voluptatibus repellendus id laudantium illo et assumenda, quidem necessitatibus, nulla obcaecati quis odio ut dolore veniam. Distinctio omnis natus eveniet dicta rem quidem maiores ut qui ea voluptatem aspernatur porro dignissimos, aliquid in, explicabo magni eos blanditiis fugiat inventore soluta sint, tempore incidunt doloremque! Accusantium facere, explicabo voluptate obcaecati voluptatem, ullam eligendi quisquam possimus in beatae, a qui delectus. Impedit sed laudantium inventore esse nihil atque odit a, libero soluta tempore aliquid deleniti. Illo perferendis non necessitatibus veritatis quae mollitia odit aut, possimus ipsum at ab corrupti, autem quis suscipit. Dolorum ullam officiis delectus magnam repellat possimus vel. Vel veniam non debitis laudantium corrupti aut libero architecto voluptate, dolore excepturi, incidunt obcaecati itaque molestiae! Id debitis eius temporibus commodi laboriosam quod deserunt quam harum vitae repellat quos enim pariatur omnis quasi corrupti, rem sunt nemo natus dolores suscipit obcaecati numquam consequatur nulla? Incidunt enim, officiis hic quos quaerat impedit praesentium aspernatur ratione accusantium corrupti animi tenetur mollitia distinctio, pariatur consectetur maiores neque fuga alias, illo commodi quae cumque necessitatibus ducimus omnis.",
    Modified_Time: "2022-07-03T22:09:59+02:00",
    Completion_Status: "Ready Property",
    Community_Latitude: "123",
    Residential_Units: null,
    Unsubscribed_Time: null,
    Agents: null,
    Rental_Deposit_Perc: null,
    Trustee_Fee: "400000",
    Property_Ref_No: "P-0000053",
    Zip_Postal_Code: "123",
    Listing_to: null,
    $in_merge: "false",
    $approval_state: "approved",
    Attachment_Count: "",
    Community: "Just Cavalli Villas",
    AgentsDB: "",
  },
  {
    _id: "",
    Owner: {
      name: "Marie-Elize Venter",
      id: "5197834000004614001",
      email: "marie@valcom.ae",
    },
    Alternative_Listing_Title: "TERTE",
    Rental_Period: null,
    $field_states: null,
    DevAccess: "Do not show",
    $sharing_permission: "full_access",
    Purchase_Deposit_Amount: "121212",
    Baths: "1",
    $state: "save",
    Number_of_Cheques: null,
    $process_flow: false,
    Balconies: "2",
    Sub_Area_Sub_Community: "Damac Towers by Paramount",
    Viewing_Options: "Viewing can be booked instantly",
    id: "5197834000008264001",
    $approval: {
      delegate: false,
      approve: false,
      reject: false,
      resubmit: false,
    },
    Created_Time: "2022-07-03T22:09:56+02:00",
    Rental_Deposit_Amount: null,
    Built_up_Area_SqM: "200.00",
    Longitude: null,
    Beds: "1",
    Reference_No_Auto: "L-000579",
    NOC_Charges_Perc: "4",
    Additional_Costs: null,
    Plot_Area_SqM: "233.00",
    Next_available: null,
    Street_No_Name: "Cresent West",
    Listing_Link_ID: "4266529000000792032",
    Greater_Area: "Dubailand",
    Country: "United Arab Emirates",
    Created_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    Transfer_Fee: "400000",
    Amenities: "Burj Khalifa View\nBoulevard View\nBroadband Ready",
    Title_Deed_Perc: "4",
    Building: "Damac Tower Paramount B",
    Hide_Purch_Price: false,
    Title_Deed_Fee: "400000",
    $review_process: {
      approve: false,
      reject: false,
      resubmit: false,
    },
    Parking_Type: "Podium 2",
    Purchase_Deposit_Percentage: "1.21",
    Record_Image:
      "a80f4895b5572856d6439a1988025ccf48ec6a723e68f23c846bd873860f11e3d5f91dc9b0659dbf5276f988d8a10226561a69b81019de3f213ee694f6c04fa124804180c0bddd6f81481f473f272951",
    Location_of_Property_Key: "MAT",
    ListCurrency: "Aruban florin",
    Plot_Area_SqFt: "2508.01",
    Hide_Rental_Price: false,
    $orchestration: false,
    Credit_Card_Accepted: false,
    Unit_No: "123123",
    Tag: [],
    Built_up_Area_SqFt: "2152.80",
    $currency_symbol: "$",
    Exclusive: "No",
    Publishing_Type: "Off-market listing",
    Latitude: null,
    $followers: null,
    Listing_Status: "Draft",
    Community_Longitude: "123",
    Digital_Currency_Accepted: "No",
    Last_Activity_Time: "2022-07-03T22:09:59+02:00",
    Name: "L-000579",
    Exclusive_Contract_Start: null,
    Unsubscribed_Mode: null,
    NOC_Charges: "400000",
    $approved: true,
    Reference_No: "L-000579",
    Community_Street_Address: "po box 25874",
    $followed: false,
    $wizard_connection_path: null,
    Year_Built: null,
    $editable: true,
    Property_Type: "Townhouse",
    City: "Dubai City",
    Utilities_Premise_Number: "123",
    Rental_Price: null,
    Parking_Qty: "7",
    Area: "Dubai Marina",
    Listing_Title: ["Golf course view", "Incredible view", "Beach access"],
    State: "Dubai",
    DigiCurrency: null,
    Unique_Extras: "ERER",
    Price_SqM: "50000",
    Purchase_Price: "10000000",
    District: "District 3",
    Property_Usage: "Holiday home",
    Trustee_Fee_Perc: "4",
    Available_for_Rent: false,
    Zoning_Tenure: null,
    Transfer_Fee_Perc: "4",
    Community_Ref_No: "C-0000004",
    Furnished: "Fully furnished",
    Price_SqFt: "4645.11",
    Exclusive_Contract_End: null,
    Ref_No_Building: null,
    Available_for_Sale: false,
    Modified_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    $review: null,
    Sale_or_Rent: "For Sale",
    Terraces: "3",
    Stories: null,
    Listing_Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam sint ad inventore aut illum placeat deserunt eveniet nemo amet, repudiandae repellendus rem ratione, nobis incidunt harum eos at! Rem voluptatibus repellendus id laudantium illo et assumenda, quidem necessitatibus, nulla obcaecati quis odio ut dolore veniam. Distinctio omnis natus eveniet dicta rem quidem maiores ut qui ea voluptatem aspernatur porro dignissimos, aliquid in, explicabo magni eos blanditiis fugiat inventore soluta sint, tempore incidunt doloremque! Accusantium facere, explicabo voluptate obcaecati voluptatem, ullam eligendi quisquam possimus in beatae, a qui delectus. Impedit sed laudantium inventore esse nihil atque odit a, libero soluta tempore aliquid deleniti. Illo perferendis non necessitatibus veritatis quae mollitia odit aut, possimus ipsum at ab corrupti, autem quis suscipit. Dolorum ullam officiis delectus magnam repellat possimus vel. Vel veniam non debitis laudantium corrupti aut libero architecto voluptate, dolore excepturi, incidunt obcaecati itaque molestiae! Id debitis eius temporibus commodi laboriosam quod deserunt quam harum vitae repellat quos enim pariatur omnis quasi corrupti, rem sunt nemo natus dolores suscipit obcaecati numquam consequatur nulla? Incidunt enim, officiis hic quos quaerat impedit praesentium aspernatur ratione accusantium corrupti animi tenetur mollitia distinctio, pariatur consectetur maiores neque fuga alias, illo commodi quae cumque necessitatibus ducimus omnis.",
    Modified_Time: "2022-07-03T22:09:59+02:00",
    Completion_Status: "Ready Property",
    Community_Latitude: "123",
    Residential_Units: null,
    Unsubscribed_Time: null,
    Agents: null,
    Rental_Deposit_Perc: null,
    Trustee_Fee: "400000",
    Property_Ref_No: "P-0000053",
    Zip_Postal_Code: "123",
    Listing_to: null,
    $in_merge: "false",
    $approval_state: "approved",
    Attachment_Count: "",
    Community: "Just Cavalli Villas",
    AgentsDB: "",
  },
  {
    _id: "",
    Owner: {
      name: "Marie-Elize Venter",
      id: "5197834000004614001",
      email: "marie@valcom.ae",
    },
    Alternative_Listing_Title: "TERTE",
    Rental_Period: null,
    $field_states: null,
    DevAccess: "Do not show",
    $sharing_permission: "full_access",
    Purchase_Deposit_Amount: "121212",
    Baths: "1",
    $state: "save",
    Number_of_Cheques: null,
    $process_flow: false,
    Balconies: "2",
    Viewing_Options: "Viewing can be booked instantly",
    id: "5197834000008264001",
    $approval: {
      delegate: false,
      approve: false,
      reject: false,
      resubmit: false,
    },
    Created_Time: "2022-07-03T22:09:56+02:00",
    Rental_Deposit_Amount: null,
    Built_up_Area_SqM: "200.00",
    Longitude: null,
    Beds: "1",
    Reference_No_Auto: "L-000579",
    NOC_Charges_Perc: "4",
    Additional_Costs: null,
    Plot_Area_SqM: "233.00",
    Next_available: null,
    Street_No_Name: "Cresent West",
    Listing_Link_ID: "4266529000000792032",
    Greater_Area: "Dubailand",
    Country: "United Arab Emirates",
    Created_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    Transfer_Fee: "400000",
    Amenities: "Burj Khalifa View\nBoulevard View\nBroadband Ready",
    Title_Deed_Perc: "4",
    Building: "Damac Tower Paramount B",
    Hide_Purch_Price: false,
    Title_Deed_Fee: "400000",
    $review_process: {
      approve: false,
      reject: false,
      resubmit: false,
    },
    Parking_Type: "Podium 2",
    Purchase_Deposit_Percentage: "1.21",
    Record_Image:
      "a80f4895b5572856d6439a1988025ccf48ec6a723e68f23c846bd873860f11e3d5f91dc9b0659dbf5276f988d8a10226561a69b81019de3f213ee694f6c04fa124804180c0bddd6f81481f473f272951",
    Location_of_Property_Key: "MAT",
    ListCurrency: "Aruban florin",
    Plot_Area_SqFt: "2508.01",
    Hide_Rental_Price: false,
    $orchestration: false,
    Credit_Card_Accepted: false,
    Unit_No: "123123",
    Tag: [],
    Built_up_Area_SqFt: "2152.80",
    $currency_symbol: "$",
    Exclusive: "No",
    Publishing_Type: "Off-market listing",
    Latitude: null,
    $followers: null,
    Listing_Status: "Draft",
    Community_Longitude: "123",
    Digital_Currency_Accepted: "No",
    Last_Activity_Time: "2022-07-03T22:09:59+02:00",
    Name: "L-000579",
    Exclusive_Contract_Start: null,
    Unsubscribed_Mode: null,
    NOC_Charges: "400000",
    $approved: true,
    Reference_No: "L-000579",
    Community_Street_Address: "po box 25874",
    $followed: false,
    $wizard_connection_path: null,
    Year_Built: null,
    $editable: true,
    Property_Type: "Townhouse",
    City: "Dubai City",
    Utilities_Premise_Number: "123",
    Rental_Price: null,
    Parking_Qty: "7",
    Area: "Dubai Marina",
    Listing_Title: ["Golf course view", "Incredible view", "Beach access"],
    State: "Dubai",
    DigiCurrency: null,
    Unique_Extras: "ERER",
    Price_SqM: "50000",
    Purchase_Price: "10000000",
    District: "District 3",
    Property_Usage: "Holiday home",
    Trustee_Fee_Perc: "4",
    Available_for_Rent: false,
    Zoning_Tenure: null,
    Transfer_Fee_Perc: "4",
    Community_Ref_No: "C-0000004",
    Furnished: "Fully furnished",
    Price_SqFt: "4645.11",
    Exclusive_Contract_End: null,
    Ref_No_Building: null,
    Available_for_Sale: false,
    Modified_By: {
      name: "Henk",
      id: "5197834000000354117",
      email: "hendrik.smit@valcom.ae",
    },
    $review: null,
    Sale_or_Rent: "For Sale",
    Terraces: "3",
    Stories: null,
    Listing_Description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam sint ad inventore aut illum placeat deserunt eveniet nemo amet, repudiandae repellendus rem ratione, nobis incidunt harum eos at! Rem voluptatibus repellendus id laudantium illo et assumenda, quidem necessitatibus, nulla obcaecati quis odio ut dolore veniam. Distinctio omnis natus eveniet dicta rem quidem maiores ut qui ea voluptatem aspernatur porro dignissimos, aliquid in, explicabo magni eos blanditiis fugiat inventore soluta sint, tempore incidunt doloremque! Accusantium facere, explicabo voluptate obcaecati voluptatem, ullam eligendi quisquam possimus in beatae, a qui delectus. Impedit sed laudantium inventore esse nihil atque odit a, libero soluta tempore aliquid deleniti. Illo perferendis non necessitatibus veritatis quae mollitia odit aut, possimus ipsum at ab corrupti, autem quis suscipit. Dolorum ullam officiis delectus magnam repellat possimus vel. Vel veniam non debitis laudantium corrupti aut libero architecto voluptate, dolore excepturi, incidunt obcaecati itaque molestiae! Id debitis eius temporibus commodi laboriosam quod deserunt quam harum vitae repellat quos enim pariatur omnis quasi corrupti, rem sunt nemo natus dolores suscipit obcaecati numquam consequatur nulla? Incidunt enim, officiis hic quos quaerat impedit praesentium aspernatur ratione accusantium corrupti animi tenetur mollitia distinctio, pariatur consectetur maiores neque fuga alias, illo commodi quae cumque necessitatibus ducimus omnis.",
    Modified_Time: "2022-07-03T22:09:59+02:00",
    Completion_Status: "Ready Property",
    Community_Latitude: "123",
    Residential_Units: null,
    Unsubscribed_Time: null,
    Agents: null,
    Rental_Deposit_Perc: null,
    Trustee_Fee: "400000",
    Property_Ref_No: "P-0000053",
    Zip_Postal_Code: "123",
    Listing_to: null,
    $in_merge: "false",
    $approval_state: "approved",
    Attachment_Count: "",
    Community: "Just Cavalli Villas",
    AgentsDB: "",
  },
];
